Make examples compile, narrow down problems to FFI
`npm run run:server` produces the following error:

```
TypeError: Cannot read property 'prototype' of undefined
```

Points to this code:

```
/**
 * Module dependencies.
 * @private
 */

var accepts = require('accepts');
var deprecate = require('depd')('express');
var isIP = require('net').isIP;
var typeis = require('type-is');
var http = require('http');
var fresh = require('fresh');
var parseRange = require('range-parser');
var parse = require('parseurl');
var proxyaddr = require('proxy-addr');

/**
 * Request prototype.
 * @public
 */

var req = Object.create(http.IncomingMessage.prototype)
```

I'm not a JS expert, so I have no idea what it is or how to fix it.